[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "wwtags"
version = "0.1.0"
description = "Wonderware tag import generator"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "openpyxl"
]

[project.scripts]
wwtags = "wwtags.cli:main"
