[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wwtags"
version = "0.4.1-beta.2"
description = "Wonderware tag import generator"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "openpyxl",
    "Pillow"
]

[tool.setuptools.package-data]
wwtags = ["*.png"]

[project.scripts]
wwtags = "wwtags.cli:main"
wwtags-gui = "wwtags.gui:main"
